-- A database name is not a database identity.
--
-- Two unrelated PostgreSQL clusters on this host both hold a database called
-- `banzami_staging`. One is the Sandbox the services actually use; the other is
-- a disused instance they cannot even route to. Every safety check on the
-- migration path compared the NAME, so both passed identically, and which one
-- got migrated depended entirely on which credential was pasted.
--
-- Nothing caught it. The name matched, the migration would have applied, the
-- receipt would have recorded success, and the deployed Sandbox would have been
-- untouched.
--
-- ── WHAT THIS BINDS ─────────────────────────────────────────────────────────
--
-- `pg_control_system().system_identifier` is generated by initdb and is unique
-- to the cluster. Recording it INSIDE the database ties the two together: if the
-- stored identifier and the live cluster's disagree, this database is not the
-- one that was stamped — it was copied, restored elsewhere, or the connection
-- points at a different cluster wearing the same database name.
--
-- The single-row shape is deliberate. An identity with two rows is not an
-- identity.

BEGIN;

CREATE TABLE IF NOT EXISTS deployment_identity (
  only_row                  boolean PRIMARY KEY DEFAULT true CHECK (only_row),
  cluster_system_identifier text        NOT NULL,
  database_name             text        NOT NULL,
  stamped_at                timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE deployment_identity IS
  'Binds this database to the cluster it was created in. The rollout gate '
  '(tools/migrate-and-verify.sh) refuses to migrate a database whose stored '
  'identifier disagrees with the live cluster, and refuses a populated database '
  'that carries no identity at all — a stranger wearing the expected name.';

-- Stamped on first migration and never rewritten. The gate compares; it does
-- not correct. A mismatch is a fact to investigate, not a field to update.
INSERT INTO deployment_identity (cluster_system_identifier, database_name)
SELECT system_identifier::text, current_database()
  FROM pg_control_system()
 WHERE NOT EXISTS (SELECT 1 FROM deployment_identity);

COMMIT;
