-- Account deletion ("Supressão de conta") — real, auditable account closure.
--
-- Until now nothing deleted an account: every "Remover conta" control in the
-- apps was a local credential wipe (logout), and the only documented data
-- deletion path was a manual email to contact@. This migration adds the two
-- schema pieces the deletion feature needs, and nothing destructive on its own:
--
--   1. Two audit actions the deletion code writes — CONSUMER_DELETED and
--      BUSINESS_DELETED. audit_log.action is CHECKed against a list and core
--      writes audit rows fire-and-forget, so an action missing from the list
--      leaves no record at all (the gap 0134/0140 were about). Additive: 0140's
--      list plus these two; the list only ever grows.
--
--   2. account_deletion_requests — the intake for the PUBLIC web request form
--      (banzami.com/supressao-de-conta), for people who cannot reach the app
--      (e.g. already uninstalled). It is NOT financial state: it holds no money
--      columns, only a handle + a contact email + the request lifecycle. A
--      verified email proves control of that email, NOT ownership of the Banzami
--      account, so a request can never execute on email+handle alone: an
--      authorized operator must record an ownership verification first. That
--      invariant is enforced here by a CHECK constraint, not left to code.
--
-- The authenticated in-app flow ("Suprimir conta" / "Suprimir conta Business")
-- does NOT use this table — it executes directly after a fresh PIN re-auth.

-- 1. Audit actions ----------------------------------------------------------
ALTER TABLE audit_log DROP CONSTRAINT audit_log_action_check;
ALTER TABLE audit_log ADD CONSTRAINT audit_log_action_check CHECK (action = ANY (ARRAY[
    'ACCOUNT_FROZEN',
    'ACCOUNT_UNFROZEN',
    'ACQUIRING_CALLBACK_RECEIVED',
    'ACQUIRING_SETTLED',
    'ADMIN_CREDIT',
    'API_KEY_REVOKED',
    'BUSINESS_ACCOUNT_TYPE_CHANGED',
    'BUSINESS_CREDENTIAL_REASSIGNED',
    'BUSINESS_DELETED',
    'CONSUMER_DELETED',
    'CONSUMER_PAY_LINK_PAID',
    'CONSUMER_SUSPENDED',
    'DEPOSIT_INITIATED',
    'DEPOSIT_SETTLED',
    'DISPUTE_OPENED',
    'DISPUTE_RESOLVED',
    'KYC_STATUS_CHANGED',
    'LEDGER_POSTING',
    'MERCHANT_SUSPENDED',
    'PAYMENT_REQUEST_PAID',
    'PAYOUT_CONFIRMED',
    'PAYOUT_INITIATED',
    'QR_PAYMENT_COMPLETED',
    'RECONCILIATION_RUN',
    'REFUND_PROCESSED',
    'RISK_FLAG_RAISED',
    'RISK_FLAG_RESOLVED',
    'SANDBOX_FUNDS_RETIRED',
    'SETTLEMENT_CONFIRMED',
    'SETTLEMENT_SUBMITTED',
    'SUSPICIOUS_ACTIVITY_DETECTED',
    'TRANSFER_COMPLETED',
    'WALLET_ACCOUNT_CLOSED',
    'WALLET_CREDIT',
    'WALLET_DEBIT'
]::text[]));

-- 2. Public web deletion-request intake -------------------------------------
-- Not financial state (no amount/account/posting columns): classified in
-- core/ledger/tests/financial_writer_guard.rs NOT_FINANCIAL_STATE. The id is
-- generated by the owning service (like consumers), so no DB default is needed.
CREATE TABLE account_deletion_requests (
    id                           UUID        PRIMARY KEY,
    -- Which kind of account the request is about.
    subject_type                 TEXT        NOT NULL CHECK (subject_type IN ('CONSUMER', 'BUSINESS')),
    -- The @banza handle the requester claims. Lower-cased, no leading '@'.
    handle                       TEXT        NOT NULL,
    -- The account the handle resolved to at execution time (a consumer id or a
    -- merchant id), captured BEFORE the Core deletion retires the handle so a
    -- retried execution does not have to re-resolve a handle that is already
    -- gone. NULL until an operator begins execution.
    subject_account_id           UUID,
    -- A contact email to verify control of (NOT proof of account ownership).
    contact_email                TEXT        NOT NULL,
    -- Lifecycle. EMAIL_VERIFIED can never jump straight to EXECUTED (see CHECK).
    status                       TEXT        NOT NULL DEFAULT 'PENDING_VERIFICATION'
                                   CHECK (status IN (
                                       'PENDING_VERIFICATION',
                                       'EMAIL_VERIFIED',
                                       'OPERATOR_REVIEW',
                                       'EXECUTED',
                                       'REJECTED',
                                       'EXPIRED'
                                   )),
    -- Email OTP, HMAC-hashed (never plaintext), mirroring identity_otp_codes.
    email_otp_hash               TEXT,
    otp_expires_at               TIMESTAMPTZ,
    otp_attempts                 INT         NOT NULL DEFAULT 0,
    -- Ownership verification, recorded by an authorized operator. Required
    -- before EXECUTED is reachable (enforced below). No PIN, no documents.
    ownership_verified_by        TEXT,
    ownership_verified_at        TIMESTAMPTZ,
    ownership_verification_result TEXT       NOT NULL DEFAULT 'PENDING'
                                   CHECK (ownership_verification_result IN ('PENDING', 'VERIFIED', 'FAILED')),
    -- Outcome + correlation.
    request_id                   TEXT,
    executed_at                  TIMESTAMPTZ,
    rejected_at                  TIMESTAMPTZ,
    outcome                      TEXT,
    created_at                   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                   TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- The ownership gate as a DB invariant: a request can only be EXECUTED when
    -- an operator has recorded a VERIFIED ownership check. Email+handle alone can
    -- never delete an account.
    CONSTRAINT account_deletion_requests_execute_needs_ownership CHECK (
        status <> 'EXECUTED'
        OR (ownership_verified_by IS NOT NULL
            AND ownership_verified_at IS NOT NULL
            AND ownership_verification_result = 'VERIFIED')
    )
);

-- Operator queue: the open requests to work, newest first.
CREATE INDEX account_deletion_requests_open_idx
    ON account_deletion_requests (created_at DESC)
    WHERE status IN ('EMAIL_VERIFIED', 'OPERATOR_REVIEW');

-- Rate-limit / lookup by handle.
CREATE INDEX account_deletion_requests_handle_idx
    ON account_deletion_requests (handle);
