import { launchChromium } from './lib/browser.mjs';
import { FlutterSemanticsDriver } from './lib/semantics-driver.mjs';
import { provisionBusiness } from './lib/business-provision.mjs';
import { businessWebSignIn } from './lib/business-signin.mjs';
const APP = process.env.APP_ORIGIN || 'https://app.banzami.com';
const { browser } = await launchChromium();
const biz = await provisionBusiness({});
const page = await (await browser.newContext()).newPage();
await page.goto(`${APP}/business`, { waitUntil: 'domcontentloaded', timeout: 45000 });
const d = new FlutterSemanticsDriver(page, { label: 'a2' });
await d.enableSemantics();
await businessWebSignIn(d, biz);
await d.waitForText('Saldo disponível', { timeout: 30000 });
const t = await d.visibleText();
console.log('  LEN:', t.length);
const i = t.indexOf('Pagamentos recentes');
console.log('  INDEX:', i);
console.log('  REGION:', JSON.stringify(i >= 0 ? t.slice(i, i + 420) : t.slice(-420)));
await browser.close(); process.exit(0);
