-- GENERATED by tools/db-authority.mjs from db/authority/runtime-authority.json. Do not edit.
--
-- The database authority of every runtime identity (WALLET-NATIVE-001, ADR-061 §2).
-- PostgreSQL privilege is the authority over financial state: only bl_core_runtime
-- may INSERT, UPDATE or DELETE a financial table. application_name (0144) is
-- detection and observability, never the authority.
--
-- Applied by the cluster superuser after every migration, in ONE transaction
-- (psql --single-transaction), so a running service never sees the window between
-- the revoke and the re-grant. Idempotent. Roles are created NOLOGIN when missing;
-- the Sandbox role bootstrap gives each its LOGIN and its own password.

DO $$
DECLARE r TEXT;
BEGIN
  FOREACH r IN ARRAY ARRAY['bl_core_runtime', 'bl_gateway_runtime', 'bl_public_api_runtime', 'bl_developer_api_runtime', 'bl_admin_api_runtime', 'bl_app_runtime'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      BEGIN
        EXECUTE format('CREATE ROLE %I NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS', r);
      EXCEPTION WHEN duplicate_object OR unique_violation THEN NULL; -- created concurrently
      END;
    END IF;
    -- A runtime identity that could bypass privileges is not bounded by them.
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r AND (rolsuper OR rolbypassrls OR rolcreaterole OR rolcreatedb OR rolreplication)) THEN
      RAISE EXCEPTION 'runtime role % holds a privilege that bypasses table grants', r;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_auth_members am JOIN pg_roles g ON g.oid = am.roleid JOIN pg_roles u ON u.oid = am.member
               WHERE u.rolname = r AND (g.rolsuper OR g.rolname IN ('bl_schema_owner', 'pg_write_all_data', 'pg_database_owner'))) THEN
      RAISE EXCEPTION 'runtime role % inherits owner or superuser authority', r;
    END IF;
  END LOOP;
END $$;

DO $$
BEGIN
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime', current_database());
END $$;

-- Start from nothing: every table, view and sequence privilege these roles hold.
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime;
REVOKE ALL ON SCHEMA public FROM bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime;
REVOKE ALL ON ALL TABLES IN SCHEMA developer FROM bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA developer FROM bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime;
REVOKE ALL ON SCHEMA developer FROM bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime;
REVOKE ALL ON ALL TABLES IN SCHEMA account_identity FROM bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA account_identity FROM bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime;
REVOKE ALL ON SCHEMA account_identity FROM bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime;

-- No routine is callable by a runtime role (none is called directly; trigger functions need no
-- EXECUTE to fire), no role but the owner creates objects, and nobody gets session-local
-- objects that could shadow a name another routine resolves.
REVOKE ALL ON ALL ROUTINES IN SCHEMA public FROM PUBLIC, bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime;
REVOKE ALL ON ALL ROUTINES IN SCHEMA developer FROM PUBLIC, bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime;
REVOKE ALL ON ALL ROUTINES IN SCHEMA account_identity FROM PUBLIC, bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE CREATE ON SCHEMA developer FROM PUBLIC;
REVOKE CREATE ON SCHEMA account_identity FROM PUBLIC;
DO $$
BEGIN
  EXECUTE format('REVOKE TEMPORARY ON DATABASE %I FROM PUBLIC', current_database());
  EXECUTE format('REVOKE TEMPORARY, CREATE ON DATABASE %I FROM bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime', current_database());
END $$;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'bl_schema_owner') THEN
    -- A routine a future migration creates is not executable by PUBLIC by default.
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner REVOKE EXECUTE ON ROUTINES FROM PUBLIC;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'bl_schema_owner') THEN
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner IN SCHEMA public REVOKE ALL ON TABLES FROM bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime;
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner IN SCHEMA public REVOKE ALL ON SEQUENCES FROM bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime;
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner IN SCHEMA developer REVOKE ALL ON TABLES FROM bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime;
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner IN SCHEMA developer REVOKE ALL ON SEQUENCES FROM bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime;
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner IN SCHEMA account_identity REVOKE ALL ON TABLES FROM bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime;
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner IN SCHEMA account_identity REVOKE ALL ON SEQUENCES FROM bl_core_runtime, bl_gateway_runtime, bl_public_api_runtime, bl_developer_api_runtime, bl_admin_api_runtime, bl_app_runtime;
  END IF;
END $$;

-- A table-level grant helper that tolerates a table a later migration will create.
CREATE OR REPLACE FUNCTION pg_temp.bz_grant(privs TEXT, tbl TEXT, role TEXT) RETURNS void LANGUAGE plpgsql AS $f$
DECLARE seq RECORD;
BEGIN
  IF to_regclass(tbl) IS NULL THEN RETURN; END IF;
  EXECUTE format('GRANT %s ON TABLE %s TO %I', privs, tbl, role);
  IF privs LIKE '%INSERT%' THEN
    FOR seq IN SELECT d.objid::regclass AS s FROM pg_depend d JOIN pg_class c ON c.oid = d.objid
               WHERE d.refobjid = to_regclass(tbl) AND c.relkind = 'S' AND d.deptype IN ('a', 'i') LOOP
      EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO %I', seq.s, role);
    END LOOP;
  END IF;
END $f$;

-- ── bl_core_runtime (core-api-staging) ──
-- Banzami Core: the only runtime identity with write authority over financial state.
GRANT USAGE ON SCHEMA public TO bl_core_runtime;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO bl_core_runtime;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'bl_schema_owner') THEN
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner IN SCHEMA public GRANT SELECT ON TABLES TO bl_core_runtime;
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner IN SCHEMA public GRANT INSERT, UPDATE, DELETE ON TABLES TO bl_core_runtime;
  END IF;
END $$;
DO $$
DECLARE t RECORD;
BEGIN
  FOR t IN SELECT format('%I.%I', n.nspname, c.relname) AS name FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
           WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p') AND format('%s.%s', n.nspname, c.relname) NOT IN ('public._sqlx_migrations') LOOP
    PERFORM pg_temp.bz_grant('INSERT, UPDATE, DELETE', t.name, 'bl_core_runtime');
  END LOOP;
END $$;

-- ── bl_gateway_runtime (api-gateway-staging) ──
-- Public API gateway, webhook delivery, realtime, proofs, Business onboarding. Calls Core for every financial operation.
GRANT USAGE ON SCHEMA public TO bl_gateway_runtime;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO bl_gateway_runtime;
GRANT USAGE ON SCHEMA developer TO bl_gateway_runtime;
GRANT SELECT ON ALL TABLES IN SCHEMA developer TO bl_gateway_runtime;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'bl_schema_owner') THEN
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner IN SCHEMA public GRANT SELECT ON TABLES TO bl_gateway_runtime;
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner IN SCHEMA developer GRANT SELECT ON TABLES TO bl_gateway_runtime;
  END IF;
END $$;
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"developer"."dev_api_request_logs"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"developer"."dev_project_sandbox_binding"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."beta_testers"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."business_link_codes"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."business_receive_point_mints"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."business_receive_points"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."handle_registry"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."merchant_access_log"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."merchant_activation_tokens"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."merchant_app_credentials"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."merchant_app_sessions"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."merchant_application_documents"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."merchant_applications"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."merchant_compliance"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."merchant_kyb_documents"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."merchant_kyb_events"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."merchant_profiles"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."merchant_team_members"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."merchants"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."transaction_proof_corrections"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."transaction_proof_verifications"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."transaction_proofs"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."webhook_deliveries"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."webhook_delivery_attempts"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."webhook_endpoints"', 'bl_gateway_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."webhook_events"', 'bl_gateway_runtime');

-- ── bl_public_api_runtime (public-api-staging) ──
-- Consumer API and Sandbox test payers. Calls Core for every financial operation.
GRANT USAGE ON SCHEMA public TO bl_public_api_runtime;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO bl_public_api_runtime;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'bl_schema_owner') THEN
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner IN SCHEMA public GRANT SELECT ON TABLES TO bl_public_api_runtime;
  END IF;
END $$;
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."customer_compliance"', 'bl_public_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."kyc_cases"', 'bl_public_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."kyc_documents"', 'bl_public_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."kyc_events"', 'bl_public_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."kyc_evidence"', 'bl_public_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."public_api_credentials"', 'bl_public_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."sandbox_test_fundings"', 'bl_public_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."sandbox_test_payers"', 'bl_public_api_runtime');

-- ── bl_developer_api_runtime (developer-api) ──
-- Developer Console, accounts and the single key authority (ADR-046). Calls Core for every financial operation.
GRANT USAGE ON SCHEMA public TO bl_developer_api_runtime;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO bl_developer_api_runtime;
GRANT USAGE ON SCHEMA developer TO bl_developer_api_runtime;
GRANT SELECT ON ALL TABLES IN SCHEMA developer TO bl_developer_api_runtime;
GRANT USAGE ON SCHEMA account_identity TO bl_developer_api_runtime;
GRANT SELECT ON ALL TABLES IN SCHEMA account_identity TO bl_developer_api_runtime;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'bl_schema_owner') THEN
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner IN SCHEMA public GRANT SELECT ON TABLES TO bl_developer_api_runtime;
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner IN SCHEMA developer GRANT SELECT ON TABLES TO bl_developer_api_runtime;
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner IN SCHEMA account_identity GRANT SELECT ON TABLES TO bl_developer_api_runtime;
  END IF;
END $$;
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"account_identity"."audit_events"', 'bl_developer_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"account_identity"."identity_otp_codes"', 'bl_developer_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"account_identity"."identity_sessions"', 'bl_developer_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"account_identity"."identity_users"', 'bl_developer_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"developer"."audit_events"', 'bl_developer_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"developer"."dev_api_keys"', 'bl_developer_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"developer"."dev_api_request_logs"', 'bl_developer_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"developer"."dev_project_sandbox_binding"', 'bl_developer_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"developer"."dev_projects"', 'bl_developer_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"developer"."dev_workspace_invites"', 'bl_developer_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"developer"."dev_workspace_members"', 'bl_developer_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"developer"."dev_workspaces"', 'bl_developer_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."webhook_deliveries"', 'bl_developer_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."webhook_endpoints"', 'bl_developer_api_runtime');

-- ── bl_admin_api_runtime (admin-api) ──
-- BANZADMIN operator API: operator accounts, KYC review, compliance cases, platform settings. Calls Core for every financial operation.
GRANT USAGE ON SCHEMA public TO bl_admin_api_runtime;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO bl_admin_api_runtime;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'bl_schema_owner') THEN
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner IN SCHEMA public GRANT SELECT ON TABLES TO bl_admin_api_runtime;
  END IF;
END $$;
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."admin_audit_log"', 'bl_admin_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."admin_login_attempts"', 'bl_admin_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."admin_mfa"', 'bl_admin_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."admin_mfa_recovery_codes"', 'bl_admin_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."admin_notifications"', 'bl_admin_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."admin_password_reset_tokens"', 'bl_admin_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."admin_users"', 'bl_admin_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."beta_testers"', 'bl_admin_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."compliance_case_notes"', 'bl_admin_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."compliance_cases"', 'bl_admin_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."customer_compliance"', 'bl_admin_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."kyc_cases"', 'bl_admin_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."kyc_events"', 'bl_admin_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."kyc_reviews"', 'bl_admin_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."platform_settings"', 'bl_admin_api_runtime');
SELECT pg_temp.bz_grant('INSERT, UPDATE, DELETE', '"public"."platform_settings_history"', 'bl_admin_api_runtime');

-- ── bl_app_runtime (operator tooling, no container) ──
-- Operator tooling on the Sandbox host (fixture sweeps, residue retirement, read-only harness queries). Mounted into no container; its password lives only in the root-only secrets directory. No financial write authority, and no write on retirement/lifecycle-truth tables (a host operator must not erase a retirement marker and reopen lifecycle eligibility — MONEY-MODEL-001).
GRANT USAGE ON SCHEMA public TO bl_app_runtime;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO bl_app_runtime;
GRANT USAGE ON SCHEMA developer TO bl_app_runtime;
GRANT SELECT ON ALL TABLES IN SCHEMA developer TO bl_app_runtime;
GRANT USAGE ON SCHEMA account_identity TO bl_app_runtime;
GRANT SELECT ON ALL TABLES IN SCHEMA account_identity TO bl_app_runtime;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'bl_schema_owner') THEN
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner IN SCHEMA public GRANT SELECT ON TABLES TO bl_app_runtime;
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner IN SCHEMA developer GRANT SELECT ON TABLES TO bl_app_runtime;
    ALTER DEFAULT PRIVILEGES FOR ROLE bl_schema_owner IN SCHEMA account_identity GRANT SELECT ON TABLES TO bl_app_runtime;
  END IF;
END $$;
DO $$
DECLARE t RECORD;
BEGIN
  FOR t IN SELECT format('%I.%I', n.nspname, c.relname) AS name FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
           WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p') AND format('%s.%s', n.nspname, c.relname) NOT IN ('public.ledger_accounts', 'public.ledger_postings', 'public.ledger_entries', 'public.wallets', 'public.consumer_wallets', 'public.wallet_accounts', 'public.wallet_account_transfers', 'public.wallet_reservations', 'public.wallet_payments', 'public.transfers', 'public.transactions', 'public.payment_sessions', 'public.payment_links', 'public.refunds', 'public.refund_events', 'public.restitution_allocations', 'public.acquiring_payments', 'public.acquiring_callbacks', 'public.consumer_deposits', 'public.payouts', 'public.app_settlements', 'public.settlements', 'public.operator_fees', 'public.split_sessions', 'public.split_contributions', 'public._sqlx_migrations', 'public.sandbox_retired_projects', 'public.sandbox_test_payers', 'public.sandbox_businesses', 'public.sandbox_link_projects') LOOP
    PERFORM pg_temp.bz_grant('INSERT, UPDATE, DELETE', t.name, 'bl_app_runtime');
  END LOOP;
END $$;
DO $$
DECLARE t RECORD;
BEGIN
  FOR t IN SELECT format('%I.%I', n.nspname, c.relname) AS name FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
           WHERE n.nspname = 'developer' AND c.relkind IN ('r', 'p') LOOP
    PERFORM pg_temp.bz_grant('INSERT, UPDATE, DELETE', t.name, 'bl_app_runtime');
  END LOOP;
END $$;
DO $$
DECLARE t RECORD;
BEGIN
  FOR t IN SELECT format('%I.%I', n.nspname, c.relname) AS name FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
           WHERE n.nspname = 'account_identity' AND c.relkind IN ('r', 'p') LOOP
    PERFORM pg_temp.bz_grant('INSERT, UPDATE, DELETE', t.name, 'bl_app_runtime');
  END LOOP;
END $$;

-- The proof, in the same transaction: every direct and indirect write path is re-verified, and
-- any violation aborts the apply (db/authority/verify-authority.sql, also run on its own).
DO $verify$
DECLARE v TEXT; problems TEXT[] := ARRAY[]::text[];
BEGIN
  -- 1. direct: INSERT, UPDATE, DELETE, TRUNCATE (MERGE and COPY need the same), REFERENCES or TRIGGER on a financial table.
  SELECT string_agg(format('%s %s %s', r, p, t), ', ') INTO v
    FROM unnest(ARRAY['bl_gateway_runtime', 'bl_public_api_runtime', 'bl_developer_api_runtime', 'bl_admin_api_runtime', 'bl_app_runtime']::text[]) r, unnest(ARRAY['public.ledger_accounts', 'public.ledger_postings', 'public.ledger_entries', 'public.wallets', 'public.consumer_wallets', 'public.wallet_accounts', 'public.wallet_account_transfers', 'public.wallet_reservations', 'public.wallet_payments', 'public.transfers', 'public.transactions', 'public.payment_sessions', 'public.payment_links', 'public.refunds', 'public.refund_events', 'public.restitution_allocations', 'public.acquiring_payments', 'public.acquiring_callbacks', 'public.consumer_deposits', 'public.payouts', 'public.app_settlements', 'public.settlements', 'public.operator_fees', 'public.split_sessions', 'public.split_contributions']::text[]) t, unnest(ARRAY['INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER']) p
   WHERE to_regclass(t) IS NOT NULL AND has_table_privilege(r, t, p);
  IF v IS NOT NULL THEN problems := problems || ('NON_CORE_DIRECT_FINANCIAL_WRITE: ' || v); END IF;
  -- 2. role membership: no runtime role is a member of anything, so it cannot SET ROLE or inherit.
  SELECT string_agg(format('%s in %s', u.rolname, g.rolname), ', ') INTO v
    FROM pg_auth_members am JOIN pg_roles g ON g.oid = am.roleid JOIN pg_roles u ON u.oid = am.member
   WHERE u.rolname = ANY (ARRAY['bl_core_runtime', 'bl_gateway_runtime', 'bl_public_api_runtime', 'bl_developer_api_runtime', 'bl_admin_api_runtime', 'bl_app_runtime']::text[]);
  IF v IS NOT NULL THEN problems := problems || ('NON_CORE_PRIVILEGE_ESCALATION_ROLE_PATHS: ' || v); END IF;
  SELECT string_agg(rolname, ', ') INTO v FROM pg_roles WHERE rolname = ANY (ARRAY['bl_core_runtime', 'bl_gateway_runtime', 'bl_public_api_runtime', 'bl_developer_api_runtime', 'bl_admin_api_runtime', 'bl_app_runtime']::text[]) AND (rolsuper OR rolbypassrls OR rolcreaterole OR rolcreatedb OR rolreplication);
  IF v IS NOT NULL THEN problems := problems || ('RUNTIME_ROLE_ATTRIBUTE_BYPASS: ' || v); END IF;
  -- 3. SECURITY DEFINER routines: only those classified, each with a pinned search_path and no runtime executor.
  SELECT string_agg(format('%s.%s', n.nspname, p.proname), ', ') INTO v FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
   WHERE p.prosecdef AND n.nspname NOT IN ('pg_catalog', 'information_schema')
     AND (format('%s.%s', n.nspname, p.proname) <> ALL (ARRAY[]::text[])
          OR NOT EXISTS (SELECT 1 FROM unnest(coalesce(p.proconfig, ARRAY[]::text[])) c WHERE c LIKE 'search_path=%' AND c NOT LIKE '%$user%' AND c NOT LIKE '%pg_temp%'));
  IF v IS NOT NULL THEN problems := problems || ('UNSAFE_SECURITY_DEFINER_FUNCTIONS: ' || v); END IF;
  -- 4. routines a runtime role may execute: none, unless classified; and never one that writes a financial table.
  SELECT string_agg(format('%s may execute %s.%s', r, n.nspname, p.proname), ', ') INTO v
    FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace,
         unnest(ARRAY['bl_gateway_runtime', 'bl_public_api_runtime', 'bl_developer_api_runtime', 'bl_admin_api_runtime', 'bl_app_runtime']::text[]) r
   WHERE n.nspname = ANY (ARRAY['public', 'developer', 'account_identity']::text[]) AND has_function_privilege(r, p.oid, 'EXECUTE')
     AND (format('%s.%s', n.nspname, p.proname) <> ALL (ARRAY[]::text[]) OR p.prosrc ~* '(insert\s+into|update|delete\s+from|merge\s+into|truncate)\s+(only\s+)?(public\.)?"?(ledger_accounts|ledger_postings|ledger_entries|wallets|consumer_wallets|wallet_accounts|wallet_account_transfers|wallet_reservations|wallet_payments|transfers|transactions|payment_sessions|payment_links|refunds|refund_events|restitution_allocations|acquiring_payments|acquiring_callbacks|consumer_deposits|payouts|app_settlements|settlements|operator_fees|split_sessions|split_contributions)"?\M');
  IF v IS NOT NULL THEN problems := problems || ('NON_CORE_EXECUTABLE_ROUTINES: ' || v); END IF;
  -- 5. a routine that writes a financial table must be classified.
  SELECT string_agg(format('%s.%s', n.nspname, p.proname), ', ') INTO v FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
   WHERE n.nspname = ANY (ARRAY['public', 'developer', 'account_identity']::text[]) AND p.prosrc ~* '(insert\s+into|update|delete\s+from|merge\s+into|truncate)\s+(only\s+)?(public\.)?"?(ledger_accounts|ledger_postings|ledger_entries|wallets|consumer_wallets|wallet_accounts|wallet_account_transfers|wallet_reservations|wallet_payments|transfers|transactions|payment_sessions|payment_links|refunds|refund_events|restitution_allocations|acquiring_payments|acquiring_callbacks|consumer_deposits|payouts|app_settlements|settlements|operator_fees|split_sessions|split_contributions)"?\M'
     AND format('%s.%s', n.nspname, p.proname) <> ALL (ARRAY['public.create_primary_wallet_account']::text[]);
  IF v IS NOT NULL THEN problems := problems || ('UNCLASSIFIED_FINANCIAL_WRITE_ROUTINES: ' || v); END IF;
  -- 6. rewrite paths: no non-SELECT rule, no INSTEAD OF trigger, no write privilege on any view.
  SELECT string_agg(format('rule %s on %s', r.rulename, r.ev_class::regclass), ', ') INTO v FROM pg_rewrite r JOIN pg_class c ON c.oid = r.ev_class JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE r.ev_type <> '1' AND n.nspname = ANY (ARRAY['public', 'developer', 'account_identity']::text[]);
  IF v IS NOT NULL THEN problems := problems || ('NON_CORE_FINANCIAL_WRITE_VIA_VIEW_OR_RULE: ' || v); END IF;
  SELECT string_agg(format('instead-of trigger %s on %s', t.tgname, t.tgrelid::regclass), ', ') INTO v FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE NOT t.tgisinternal AND (t.tgtype & 64) <> 0 AND n.nspname = ANY (ARRAY['public', 'developer', 'account_identity']::text[]);
  IF v IS NOT NULL THEN problems := problems || ('NON_CORE_FINANCIAL_WRITE_VIA_VIEW_OR_RULE: ' || v); END IF;
  SELECT string_agg(format('%s %s %s.%s', r, p, n.nspname, c.relname), ', ') INTO v FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace,
         unnest(ARRAY['bl_gateway_runtime', 'bl_public_api_runtime', 'bl_developer_api_runtime', 'bl_admin_api_runtime', 'bl_app_runtime']::text[]) r, unnest(ARRAY['INSERT','UPDATE','DELETE','TRUNCATE']) p
   WHERE c.relkind IN ('v', 'm', 'f') AND n.nspname = ANY (ARRAY['public', 'developer', 'account_identity']::text[]) AND has_table_privilege(r, c.oid, p);
  IF v IS NOT NULL THEN problems := problems || ('NON_CORE_FINANCIAL_WRITE_VIA_VIEW_OR_RULE: ' || v); END IF;
  -- 7. object creation: no runtime role creates in any schema, creates schemas, or holds TEMP.
  SELECT string_agg(format('%s CREATE on %s', r, n.nspname), ', ') INTO v FROM pg_namespace n,
         unnest(ARRAY['bl_core_runtime', 'bl_gateway_runtime', 'bl_public_api_runtime', 'bl_developer_api_runtime', 'bl_admin_api_runtime', 'bl_app_runtime']::text[]) r WHERE n.nspname NOT LIKE 'pg\_%' AND n.nspname <> 'information_schema' AND has_schema_privilege(r, n.oid, 'CREATE');
  IF v IS NOT NULL THEN problems := problems || ('NON_CORE_SEARCH_PATH_PRIVILEGE_ESCALATION: ' || v); END IF;
  SELECT string_agg(r, ', ') INTO v FROM unnest(ARRAY['bl_core_runtime', 'bl_gateway_runtime', 'bl_public_api_runtime', 'bl_developer_api_runtime', 'bl_admin_api_runtime', 'bl_app_runtime']::text[]) r WHERE has_database_privilege(r, current_database(), 'TEMP') OR has_database_privilege(r, current_database(), 'CREATE');
  IF v IS NOT NULL THEN problems := problems || ('NON_CORE_SEARCH_PATH_PRIVILEGE_ESCALATION: TEMP or CREATE on the database for ' || v); END IF;
  -- 8. default privileges: a future table gives no runtime role but Core a write; a future routine is not PUBLIC.
  SELECT string_agg(format('%s in %s: %s', d.defaclobjtype, coalesce(d.defaclnamespace::regnamespace::text, '(all)'), a.grantee::regrole), ', ') INTO v
    FROM pg_default_acl d, aclexplode(d.defaclacl) a
   WHERE a.grantee <> 0 AND a.grantee::regrole::text = ANY (ARRAY['bl_gateway_runtime', 'bl_public_api_runtime', 'bl_developer_api_runtime', 'bl_admin_api_runtime', 'bl_app_runtime']::text[])
     AND ((d.defaclobjtype = 'r' AND a.privilege_type IN ('INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER')) OR d.defaclobjtype IN ('f', 'n'));
  IF v IS NOT NULL THEN problems := problems || ('DATABASE_AUTHORITY_DEFAULT_PRIVILEGES: ' || v); END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'bl_schema_owner') AND NOT EXISTS (
       SELECT 1 FROM pg_default_acl d WHERE d.defaclrole = (SELECT oid FROM pg_roles WHERE rolname = 'bl_schema_owner') AND d.defaclnamespace = 0 AND d.defaclobjtype = 'f'
          AND NOT EXISTS (SELECT 1 FROM aclexplode(d.defaclacl) a WHERE a.grantee = 0)) THEN
    problems := problems || 'DATABASE_AUTHORITY_DEFAULT_PRIVILEGES: routines created by bl_schema_owner are executable by PUBLIC by default'::text;
  END IF;
  -- 9. every table with a money or ledger column is financial (and guarded) or classified.
  SELECT string_agg(DISTINCT c.table_name, ', ') INTO v FROM information_schema.columns c JOIN pg_class k ON k.relname = c.table_name JOIN pg_namespace n ON n.oid = k.relnamespace AND n.nspname = c.table_schema
   WHERE c.table_schema = 'public' AND k.relkind IN ('r', 'p')
     AND (c.column_name LIKE '%amount_minor%' OR c.column_name IN ('account_id', 'available_account_id', 'posting_id', 'ledger_posting_id'))
     AND c.table_name <> ALL (ARRAY['ledger_accounts', 'ledger_postings', 'ledger_entries', 'wallets', 'consumer_wallets', 'wallet_accounts', 'wallet_account_transfers', 'wallet_reservations', 'wallet_payments', 'transfers', 'transactions', 'payment_sessions', 'payment_links', 'refunds', 'refund_events', 'restitution_allocations', 'acquiring_payments', 'acquiring_callbacks', 'consumer_deposits', 'payouts', 'app_settlements', 'settlements', 'operator_fees', 'split_sessions', 'split_contributions', 'transaction_proofs', 'disputes', 'payment_requests', 'consumer_pay_links', 'qr_codes', 'velocity_counters', 'sandbox_test_fundings', 'acquiring_reconciliation_items', 'reconciliation_attempts', 'boundary_reconciliation_runs', 'boundary_reconciliation_items', 'collections', 'collection_shares', 'payment_intents']::text[]);
  IF v IS NOT NULL THEN problems := problems || ('UNCLASSIFIED_NEW_FINANCIAL_DB_OBJECTS: ' || v); END IF;
  SELECT string_agg(t, ', ') INTO v FROM unnest(ARRAY['ledger_accounts', 'ledger_postings', 'ledger_entries', 'wallets', 'consumer_wallets', 'wallet_accounts', 'wallet_account_transfers', 'wallet_reservations', 'wallet_payments', 'transfers', 'transactions', 'payment_sessions', 'payment_links', 'refunds', 'refund_events', 'restitution_allocations', 'acquiring_payments', 'acquiring_callbacks', 'consumer_deposits', 'payouts', 'app_settlements', 'settlements', 'operator_fees', 'split_sessions', 'split_contributions']::text[]) t
   WHERE to_regclass('public.' || t) IS NOT NULL AND NOT EXISTS (SELECT 1 FROM pg_trigger g WHERE g.tgrelid = to_regclass('public.' || t) AND g.tgname = t || '_core_only_writer');
  IF v IS NOT NULL THEN problems := problems || ('UNCLASSIFIED_NEW_FINANCIAL_DB_OBJECTS: unguarded financial table ' || v); END IF;
  IF cardinality(problems) > 0 THEN
    RAISE EXCEPTION 'DB_AUTHORITY_VIOLATION: %', array_to_string(problems, ' | ');
  END IF;
END $verify$;
