#!/usr/bin/env bash
# REFERENCE_APPLICATION_DOA — an integration test OF DOA, the reference application:
# it acts in DOA's real tenant on purpose, so it runs only when asked
# (BANZAMI_ALLOW_DOA_TENANT_WRITES=1). A generic harness never names DOA —
# it builds a tenant of its own (tests/phase0/lib/synthetic-tenant.sh).
#
# DOA's project is bound to @doa, and that binding is sealed.
#
# The binding is what decides who gets paid. A payment session created with
# DOA's key credits the account the binding names — DOA sends no merchant id
# and no wallet id, deliberately, because a second source of truth for "who
# receives this money" is a second thing that can be wrong.
#
# It was wrong once: the project pointed at a fixture merchant created by a
# harness, carrying an autogenerated handle. It was corrected while still
# unsealed, which is exactly the window ADR-055 leaves open, and the old
# binding is DISABLED rather than deleted.
#
# So this asserts the end state, in the deployed database:
#
#   exactly one ACTIVE binding on the project
#   it names the merchant that owns the handle 'doa'
#   artifact_created is true — the seal is on, so it can no longer be moved
#   the retired binding is still there, disabled, not erased
#
# ADR-055's own test proves the seal REFUSES changes. This proves the sealed
# binding is the RIGHT one, which no amount of immutability gives you.
#
# Usage: bash tests/phase0/doa-canonical-binding.sh
set -uo pipefail
REMOTE="${BANZAMI_REMOTE:-root@217.160.9.248}"
PROJECT="${DOA_PROJECT_ID:-6367749d-ba77-47b6-80bd-982382ddd1c9}"

# The canonical remote-execution contract: prove the host, run there, and return
# the proof's own exit status. See tools/ops/lib/remote.sh.
for _p in "$(dirname "$0")/remote.sh" "$(dirname "$0")/lib/remote.sh" \
          "$(dirname "$0")/../lib/remote.sh" "$(dirname "$0")/../../tools/ops/lib/remote.sh"; do
  [ -f "$_p" ] && { . "$_p"; break; }
done
command -v remote_self_or_continue >/dev/null 2>&1 \
  || { echo "✗ tools/ops/lib/remote.sh not found — refusing to run without the host guard" >&2; exit 2; }
remote_self_or_continue 

PG=$(docker ps --format '{{.Names}}' | grep postgres | grep bzsandbox | head -1)
CORE=$(docker ps --format '{{.Names}}' | grep core-api-staging | head -1)
PW=$(docker exec "$CORE" sh -c 'cat /run/secrets/db_url' | sed -E 's#.*://[^:]+:([^@]+)@.*#\1#')
q(){ docker exec -e PGPASSWORD="$PW" "$PG" psql -U bl_app_runtime -d banzami_staging -At -c "$1"; }

PASS=0; FAIL=0
chk(){ if [ "$2" = "$3" ]; then echo "  $1 PASS ($2)"; PASS=$((PASS+1));
       else echo "  $1 FAIL (got '$2' want '$3')"; FAIL=$((FAIL+1)); fi; }

echo "DOA canonical binding — project $PROJECT"
echo "  $(q "select name from developer.dev_projects where id='$PROJECT'")"

chk EXACTLY_ONE_ACTIVE_BINDING \
  "$(q "select count(*) from developer.dev_project_sandbox_binding where project_id='$PROJECT' and state='ACTIVE'")" "1"

# The handle is the identity a person recognises; the merchant id is the one the
# money follows. This checks they are the same thing.
chk ACTIVE_BINDING_IS_THE_DOA_HANDLE \
  "$(q "select count(*) from developer.dev_project_sandbox_binding b
        join handle_registry h on h.owner_id = b.merchant_id
        where b.project_id='$PROJECT' and b.state='ACTIVE' and h.handle='doa'")" "1"

chk BINDING_IS_SEALED \
  "$(q "select artifact_created from developer.dev_project_sandbox_binding
        where project_id='$PROJECT' and state='ACTIVE'")" "t"

# The correction is part of the record. A binding that was replaced and then
# vanished would leave no trace that the project ever pointed elsewhere.
chk RETIRED_BINDING_KEPT \
  "$(q "select case when count(*) >= 1 then 'yes' else 'no' end
        from developer.dev_project_sandbox_binding where project_id='$PROJECT' and state='DISABLED'")" "yes"

chk RETIRED_BINDING_WAS_NEVER_SEALED \
  "$(q "select count(*) from developer.dev_project_sandbox_binding
        where project_id='$PROJECT' and state='DISABLED' and artifact_created")" "0"

echo
[ "$FAIL" -eq 0 ] && echo "DOA_CANONICAL_BINDING: PASS=$PASS FAIL=0" || echo "DOA_CANONICAL_BINDING: PASS=$PASS FAIL=$FAIL"
exit $([ "$FAIL" -eq 0 ] && echo 0 || echo 1)
