#!/usr/bin/env bash
# REFERENCE_APPLICATION_DOA — an integration test OF DOA, the reference application:
# it acts in DOA's real tenant on purpose, so it runs only when asked
# (BANZAMI_ALLOW_DOA_TENANT_WRITES=1). A generic harness never names DOA —
# it builds a tenant of its own (tests/phase0/lib/synthetic-tenant.sh).
#
# DOA's project is bound to @doa, and that binding is sealed.
#
# The binding is what decides who gets paid. A payment session created with
# DOA's key credits the account the binding names — DOA sends no merchant id
# and no wallet id, deliberately, because a second source of truth for "who
# receives this money" is a second thing that can be wrong.
#
# It was wrong once: the project pointed at a fixture merchant created by a
# harness, carrying an autogenerated handle. It was corrected while still
# unsealed, which is exactly the window ADR-055 leaves open, and the old
# binding is DISABLED rather than deleted.
#
# So this asserts the end state, in the deployed database:
#
#   exactly one ACTIVE binding on the project
#   it names the merchant that owns the handle 'doa'
#   artifact_created is true — the seal is on, so it can no longer be moved
#   the retired binding is still there, disabled, not erased
#
# ADR-055's own test proves the seal REFUSES changes. This proves the sealed
# binding is the RIGHT one, which no amount of immutability gives you.
#
# Usage: bash tests/phase0/doa-canonical-binding.sh
set -uo pipefail
REMOTE="${BANZAMI_REMOTE:-root@217.160.9.248}"
# DOA's canonical project, discovered rather than pinned. The default used to be
# a literal id that no longer exists: the harness printed a blank project name
# and failed every assertion, which reads as "DOA's binding is broken" when what
# had happened is that the harness was pointed at nothing. DOA_PROJECT_ID still
# overrides, for asking about a specific project on purpose.
PROJECT="${DOA_PROJECT_ID:-}"

# The canonical remote-execution contract: prove the host, run there, and return
# the proof's own exit status. See tools/ops/lib/remote.sh.
for _p in "$(dirname "$0")/remote.sh" "$(dirname "$0")/lib/remote.sh" \
          "$(dirname "$0")/../lib/remote.sh" "$(dirname "$0")/../../tools/ops/lib/remote.sh"; do
  [ -f "$_p" ] && { . "$_p"; break; }
done
command -v remote_self_or_continue >/dev/null 2>&1 \
  || { echo "✗ tools/ops/lib/remote.sh not found — refusing to run without the host guard" >&2; exit 2; }
remote_self_or_continue 

PG=$(docker ps --format '{{.Names}}' | grep postgres | grep bzsandbox | head -1)
CORE=$(docker ps --format '{{.Names}}' | grep core-api-staging | head -1)
PW=$(docker exec "$CORE" sh -c 'cat /run/secrets/db_url' | sed -E 's#.*://[^:]+:([^@]+)@.*#\1#')
q(){ docker exec -e PGPASSWORD="$PW" "$PG" psql -U bl_app_runtime -d banzami_staging -At -c "$1"; }

PASS=0; FAIL=0
chk(){ if [ "$2" = "$3" ]; then echo "  $1 PASS ($2)"; PASS=$((PASS+1));
       else echo "  $1 FAIL (got '$2' want '$3')"; FAIL=$((FAIL+1)); fi; }

# Discover DOA's canonical project when one was not named: the ACTIVE project
# whose ACTIVE binding names the merchant that owns the handle 'doa'. That is
# the definition the assertions below test against, so finding it this way
# cannot smuggle in a project that would trivially pass them — the binding and
# the seal are still checked, and a second candidate is a failure in itself.
if [ -z "$PROJECT" ]; then
  FOUND=$(q "select p.id from developer.dev_projects p
               join developer.dev_project_sandbox_binding b on b.project_id = p.id and b.state='ACTIVE'
               join business_public_identities h on h.merchant_id = b.merchant_id
              where p.status='ACTIVE' and h.handle='doa'")
  COUNT=$(printf '%s\n' "$FOUND" | grep -c . )
  if [ "${COUNT:-0}" -ne 1 ]; then
    echo "DOA canonical binding — EXPECTED exactly one ACTIVE project bound to @doa, found ${COUNT:-0}"
    echo "DOA_CANONICAL_BINDING: PASS=0 FAIL=1"
    exit 1
  fi
  PROJECT="$FOUND"
fi

echo "DOA canonical binding — project $PROJECT"
echo "  $(q "select name from developer.dev_projects where id='$PROJECT'")"

chk EXACTLY_ONE_ACTIVE_BINDING \
  "$(q "select count(*) from developer.dev_project_sandbox_binding where project_id='$PROJECT' and state='ACTIVE'")" "1"

# The handle is the identity a person recognises; the merchant id is the one the
# money follows. This checks they are the same thing.
chk ACTIVE_BINDING_IS_THE_DOA_HANDLE \
  "$(q "select count(*) from developer.dev_project_sandbox_binding b
        join handle_registry h on h.owner_id = b.merchant_id
        where b.project_id='$PROJECT' and b.state='ACTIVE' and h.handle='doa'")" "1"

chk BINDING_IS_SEALED \
  "$(q "select artifact_created from developer.dev_project_sandbox_binding
        where project_id='$PROJECT' and state='ACTIVE'")" "t"

# A binding that was replaced must not VANISH — a project that once pointed
# elsewhere should still show that it did. But a project that was never rebound
# has no retired binding to keep, and after the 2026-09-11 clean slate DOA is
# exactly that. Asserting one exists made a correctly clean tenant look broken.
#
# So the property is conditional, and the unconditional half is the one that
# matters: whatever retired bindings exist, none of them was ever sealed.
RETIRED=$(q "select count(*) from developer.dev_project_sandbox_binding
             where project_id='$PROJECT' and state='DISABLED'")
if [ "${RETIRED:-0}" -gt 0 ]; then
  chk RETIRED_BINDING_KEPT "yes" "yes"
else
  echo "  RETIRED_BINDING_KEPT n/a (this project was never rebound, so there is no retired binding to keep)"
fi

chk RETIRED_BINDING_WAS_NEVER_SEALED \
  "$(q "select count(*) from developer.dev_project_sandbox_binding
        where project_id='$PROJECT' and state='DISABLED' and artifact_created")" "0"

echo
[ "$FAIL" -eq 0 ] && echo "DOA_CANONICAL_BINDING: PASS=$PASS FAIL=0" || echo "DOA_CANONICAL_BINDING: PASS=$PASS FAIL=$FAIL"
exit $([ "$FAIL" -eq 0 ] && echo 0 || echo 1)
