// Code generated by tools/gen-pilot-limits.mjs. DO NOT EDIT.
//
// Source of truth: core/compliance/src/pilot.rs. Extracted, never restated:
// a refusal that names a different maximum from the one Core enforces would
// send a payer to retry an amount that can never pass.
//
// Regenerate with: make gen-pilot-limits

package handler

// pilotPerPaymentMinor is CONSUMER_PER_PAYMENT_MINOR: the most a single Sandbox payment may be (minor units).
const pilotPerPaymentMinor int64 = 5000000

// pilotPerReceiveMinor is MERCHANT_PER_RECEIVE_MINOR: the most a Business may receive in a single Sandbox payment (minor units).
const pilotPerReceiveMinor int64 = 5000000

// pilotConsumerMaxBalanceMinor is CONSUMER_MAX_BALANCE_MINOR: the most a Sandbox wallet may hold, and so the most a single top-up can add (minor units).
const pilotConsumerMaxBalanceMinor int64 = 5000000
