/**
 * Consumer factory: register a fresh consumer through the REAL Flutter UI in an
 * isolated browser context (CONSUMER_BROWSER_CONTEXT_ISOLATION). Returns the
 * live page + driver + page objects so a proof can keep driving that consumer.
 *
 * The PIN is generated by the caller and passed in; it is used to drive the
 * keypad and is never logged or returned.
 */
import { FlutterSemanticsDriver } from './semantics-driver.mjs';
import { WelcomePage } from '../pages/welcome.mjs';
import { CreateAccountPage } from '../pages/create-account.mjs';
import { PinPage } from '../pages/pin.mjs';
import { HomePage } from '../pages/home.mjs';

export const APP = process.env.APP_WEB_URL ?? 'https://app.banzami.com';

/** Open a fresh isolated context at a URL and return { context, page, driver }. */
export async function freshContext(browser, { url = APP + '/', label = 'consumer' } = {}) {
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 45000 });
  const driver = new FlutterSemanticsDriver(page, { label });
  return { context, page, driver };
}

/**
 * Register a fresh consumer end-to-end and land on Home.
 * @returns { context, page, driver, home, handle, name }
 */
export async function registerConsumer(browser, { handle, name, pin, label = 'consumer' }) {
  const { context, page, driver } = await freshContext(browser, { label });
  const welcome = new WelcomePage(driver);
  const create = new CreateAccountPage(driver);
  const pinPage = new PinPage(driver);
  const home = new HomePage(driver);

  await welcome.reach();
  await welcome.tapCreateAccount();
  await create.reach();
  await create.fill({ handle, name });
  await create.submit();
  await pinPage.createDuringOnboarding(pin);
  await home.reach();

  return { context, page, driver, home, handle, name };
}
