// Code generated by tools/gen-pilot-limits.mjs. DO NOT EDIT.
//
// Source of truth:
//   core/compliance/src/pilot.rs          — the constants (owner decision D1)
//   core/compliance/src/pilot_enforce.rs  — the read-only volume queries
//
// Extracted rather than restated. A preflight that measured headroom
// differently from the engine that enforces it would clear a run the ledger
// then refuses halfway through — worse than no preflight at all.
//
// Regenerate with: make gen-pilot-limits

package validation

// GlobalRolling24hMinor is GLOBAL_ROLLING_24H_MINOR: every merchant, trailing 24 hours.
const GlobalRolling24hMinor int64 = 200000000

// GlobalRolling30dMinor is GLOBAL_ROLLING_30D_MINOR: every merchant, trailing 30 days.
const GlobalRolling30dMinor int64 = 6000000000

// MerchantRolling24hMinor is MERCHANT_ROLLING_24H_MINOR: one merchant, trailing 24 hours.
const MerchantRolling24hMinor int64 = 100000000

// MerchantRolling30dMinor is MERCHANT_ROLLING_30D_MINOR: one merchant, trailing 30 days.
const MerchantRolling30dMinor int64 = 3000000000

// AggregateFundsCapMinor is AGGREGATE_FUNDS_MINOR: the Sandbox synthetic-supply fuse — value issued and not destroyed, environment-wide (not a wallet limit).
const AggregateFundsCapMinor int64 = 25000000000

// QueryGlobalRollingVolume measures merchant-credit volume across EVERY
// merchant inside a rolling window. $1 is a Postgres interval literal.
// Read-only: it counts history, it never writes it.
const QueryGlobalRollingVolume = "SELECT COALESCE(SUM(le.amount_minor), 0)::bigint FROM ledger_entries le WHERE le.entry_type = 'CREDIT' AND le.created_at >= now() - $1::interval AND le.account_id IN (SELECT available_account_id FROM wallets)"

// QueryMerchantRollingVolume measures ONE merchant's available account inside
// a rolling window. $1 is the account id, $2 the interval literal.
const QueryMerchantRollingVolume = "SELECT COALESCE(SUM(amount_minor), 0)::bigint FROM ledger_entries WHERE entry_type = 'CREDIT' AND account_id = $1 AND created_at >= now() - $2::interval"

// QueryAggregateFunds measures the synthetic supply: value issued into the
// environment and not destroyed, read at the system boundary (the net debit
// position of the EXTERNAL_TRANSIT and EXTERNAL_BACKING accounts). A movement
// between two wallets cannot change it. Read-only.
const QueryAggregateFunds = "SELECT COALESCE(SUM(CASE WHEN le.entry_type = 'DEBIT' THEN le.amount_minor ELSE -le.amount_minor END), 0)::bigint FROM ledger_entries le JOIN ledger_accounts la ON la.id = le.account_id WHERE la.system_role IN ('EXTERNAL_TRANSIT', 'EXTERNAL_BACKING')"
