// Code generated by tools/gen-pilot-limits.mjs. DO NOT EDIT.
//
// Source of truth:
//   core/compliance/src/pilot.rs          — the constants (owner decision D1)
//   core/compliance/src/pilot_enforce.rs  — the read-only volume queries
//
// Extracted rather than restated. A preflight that measured headroom
// differently from the engine that enforces it would clear a run the ledger
// then refuses halfway through — worse than no preflight at all.
//
// Regenerate with: make gen-pilot-limits

package validation

// GlobalRolling24hMinor is GLOBAL_ROLLING_24H_MINOR: every merchant, trailing 24 hours.
const GlobalRolling24hMinor int64 = 50000000

// GlobalRolling30dMinor is GLOBAL_ROLLING_30D_MINOR: every merchant, trailing 30 days.
const GlobalRolling30dMinor int64 = 400000000

// MerchantRolling24hMinor is MERCHANT_ROLLING_24H_MINOR: one merchant, trailing 24 hours.
const MerchantRolling24hMinor int64 = 25000000

// MerchantRolling30dMinor is MERCHANT_ROLLING_30D_MINOR: one merchant, trailing 30 days.
const MerchantRolling30dMinor int64 = 100000000

// QueryGlobalRollingVolume measures merchant-credit volume across EVERY
// merchant inside a rolling window. $1 is a Postgres interval literal.
// Read-only: it counts history, it never writes it.
const QueryGlobalRollingVolume = "SELECT COALESCE(SUM(le.amount_minor), 0)::bigint FROM ledger_entries le WHERE le.entry_type = 'CREDIT' AND le.created_at >= now() - $1::interval AND le.account_id IN (SELECT available_account_id FROM wallets)"

// QueryMerchantRollingVolume measures ONE merchant's available account inside
// a rolling window. $1 is the account id, $2 the interval literal.
const QueryMerchantRollingVolume = "SELECT COALESCE(SUM(amount_minor), 0)::bigint FROM ledger_entries WHERE entry_type = 'CREDIT' AND account_id = $1 AND created_at >= now() - $2::interval"
